title: Chia
author:
  name: Chia Network
  email: 'hello@chia.net'
blog:
  route: ''
metadata:
    description: 'Chia is new way to approach digital money. Green, global, and helping you grow'

menu:
  - text: "Blog"
    url: "https://medium.com/@chia_network"

taxonomies: [category,tag,month]
redirects:
    /changelog: /blog/the-urban-jungle
routes:
    /something/else: /blog/focus-and-blur
    /another/one/(.*): /blog/$1
